### ISSUE TITLE
①画像アップロードしていない状態で登録して、検索した場合にエラー発生

### ISSUE THREAD

**Issue by RyujiTakami** [libertyfish-co/Looks-yum#13]
## 再現方法

1. 画像アップロードしない状態で登録
1. 登録したfoodを検索する

## 事象
画像アップロードしていない状態で登録して、検索した場合にエラー発生

**Comment by mk-goldfish** [comment]
#17 として修正を図っており、同件の結合後は支障なくなる見込み。
また、

> 画像アップロードしない状態で登録

これについては #7 として抜本的に対策される予定。

**Comment by mk-goldfish** [comment]
#17 の結合完了をもって問題がなくなっているはずなので、クローズしておきます。
