### ISSUE TITLE
初期表示の検索画面で、空白で検索するとエラー

### ISSUE THREAD

**Issue by hironosukewatanabe** [libertyfish-co/Looks-yum#4]
**再現手順**
初期表示の検索画面で、検索項目を空白にしてsearchボタンを押下する。

**エラーメッセージは下記の通りです。**
Showing /app/app/views/foods/index.html.erb where line #94 raised:
Can't resolve image into URL: to_model delegated to attachment, but attachment is nil

Ruby on Rails オープンソース体験会 #1

**Comment by mk-goldfish** [comment]
付帯のコードに関しては以下の通り。

```erb
<span class="image_part"><%= image_tag food.image, class: "image_size" %></span>
```

`food.image` が未定義になっている(= `nil` だと認識している) 場合、これを No Image に置き換える、または `food.image` を必須の値とする必要がある。

**Comment by shunogu** [comment]
`food.image`に対してバリデーションが足りていないので、`food.image`は必須項目となるよう修正する必要がある。

**Comment by mk-goldfish** [comment]
> `food.image` が未定義になっている(= `nil` だと認識している) 場合、これを No Image に置き換える、または `food.image` を必須の値とする必要がある。

これについては #17 として解消が図られる予定。

**Comment by mk-goldfish** [comment]
#17 にて「同エラーの発生は抑制されている」のでクローズ。
必須項目化についてはまだ。
