### ISSUE TITLE
エラーメッセージについて

### ISSUE THREAD

**Issue by hiroki-yui0718** [libertyfish-co/Looks-yum#52]
日本語化にした方がわかりやすい

**Comment by YInoue531LF** [comment]
[エラーメッセージの日本語化 #61](https://github.com/libertyfish-co/Looks-yum/pull/61)で日本語化対応のプルリクが出てます

**Comment by soruma** [comment]
Fixed #61

**Comment by soruma** [comment]
@hiroki-yui0718 問題の起案ありがとうございました。
