### ISSUE TITLE
ログイン前のsearchボタンが無効なので、意味がないボタンになっている。

### ISSUE THREAD

**Issue by ghost** [libertyfish-co/Looks-yum#9]
削除するか、検索機能を追加する必要がある。

**Comment by mk-goldfish** [comment]
当初記載者は不明になってしまっているが、「ログインができている / いない」にかかわらず **検索実行に関しては特に支障なく実行ができる** ようなので、何らかの認識誤りである可能性が高い。再現性不明として一旦クローズしておく。

あるいは #17 の関連だった可能性もある？
